service: node-serverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2
  timeout: 30

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:CreateTable   # Add permission to create tables
      Resource: arn:aws:dynamodb:us-west-2:850995578388:table/* # Wildcard for all tables in the region

plugins:
  - serverless-offline                # For local development
  - serverless-dotenv-plugin          # Load environment variables (optional)
  - serverless-iam-roles-per-function # Enables function-specific IAM roles

functions:
  createUser:
    handler: handlers/userHandler.createUser
    events:
      - http:
          path: users/createUser
          method: post

  getAllUsers:
    handler: handlers/userHandler.getAllUsers
    events:
      - http:
          path: users/getAllUsers
          method: get
